### ISSUE TITLE
Deprecation warnings > 1.13

### ISSUE THREAD

**Issue by ZackMattor** [johnotander/ember-cli-weather-icons#9]
Seeing some deprecation errors regarding how you are defining your helpers. Should be using `Ember.Helper.helper` now. Probably wont work in Ember 2.x

**Comment by johnotander** [comment]
Thanks for reporting @ZackMattor. It had been a _very_ long time since I updated this addon :blush: . I've now removed the helper API call entirely, opting for a component instead, and added more thorough tests. Everything should be up to date now : )

You can install the latest version (`3.0.0`) with `ember install ember-cli-weather-icons`. Let me know if you encounter any issues.

**Comment by ZackMattor** [comment]
Damn man... :+1: you saved me a bunch of work :) You're the best! :rocket:

**Comment by johnotander** [comment]
:heart:
